import type { Metadata } from "next";
import { ArrowLeft, ShieldCheck } from "lucide-react";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy and Data Use · Angry Cat Oral Boards",
  description: "How Angry Cat Oral Boards handles practice-session data.",
};

export default function PrivacyPage() {
  return (
    <main className="report-library-shell privacy-shell">
      <nav className="report-library-nav" aria-label="Privacy navigation">
        <Link className="report-library-brand" href="/">
          <span className="brand-mark small" aria-hidden="true">AC</span>
          <span>
            <strong>Angry Cat</strong>
            <small>Privacy and data use</small>
          </span>
        </Link>
        <div className="report-library-nav-actions">
          <Link href="/reports">Report library</Link>
        </div>
      </nav>

      <article className="privacy-card">
        <Link className="report-back-link" href="/">
          <ArrowLeft size={18} aria-hidden="true" /> Back to the interviewer
        </Link>
        <div className="privacy-heading">
          <div className="report-access-icon"><ShieldCheck aria-hidden="true" /></div>
          <div>
            <p className="privacy-kicker">Practice data only</p>
            <h1>Privacy and data use</h1>
          </div>
        </div>

        <p className="privacy-lede">
          Angry Cat is an educational pediatric oral-boards practice tool. Use fictional cases
          and answers only. Do not enter protected health information or any information that
          could identify a patient, child, guardian, colleague, or practice.
        </p>

        <section>
          <h2>What the hosted interviewer receives</h2>
          <p>
            When you use voice mode, the browser streams microphone audio while the interviewer is
            listening. Typed answers are sent when you submit them. The hosted interviewer and its
            configured AI provider use those inputs to produce questions, captions, transcripts,
            and evaluation feedback.
          </p>
          <p>
            The browser receives a short-lived, server-issued session token. The room identifier
            is generated by the server and kept in page memory; it is not placed in local or
            session storage. Report access uses an HttpOnly, Secure cookie.
          </p>
        </section>

        <section>
          <h2>Reports and public sharing</h2>
          <p>
            Completed reports are stored in the deployment&apos;s private Cloudflare R2 bucket by
            default. The public report library is disabled by default and reads from a separate
            curated public collection when an operator explicitly enables it. A report should be
            redacted and reviewed before an operator copies it into that collection.
          </p>
          <p>
            This repository does not provide user accounts or a self-service deletion control.
            Retention and deletion for a hosted deployment are controlled by its operator. If you
            use a deployment you do not control, ask that operator about its retention policy.
          </p>
        </section>

        <section>
          <h2>What not to enter</h2>
          <ul>
            <li>Names, dates of birth, addresses, phone numbers, or email addresses.</li>
            <li>Medical record numbers, insurance details, photographs, or identifiable narratives.</li>
            <li>Credentials, API keys, confidential workplace information, or real patient notes.</li>
          </ul>
        </section>

        <section>
          <h2>Educational disclaimer</h2>
          <p>
            This tool is for study and simulation. Its questions and evaluations are not medical
            advice, a diagnosis, or a substitute for current professional guidance, supervision,
            or the AAPD reference materials.
          </p>
        </section>

        <p className="privacy-updated">
          If you find a security or privacy issue in this repository, please report it privately to
          the repository owner before sharing sensitive details publicly.
        </p>
      </article>
    </main>
  );
}
